export const videos = [
  {
    id: '1',
    thumbnail: require('../assets/thumbnail-1.jpg'),
    profile: require('../assets/profile-1.png'),
    title: 'Porsche 992 GT3 RS // 306km/h REVIEW',
    subtitle: 'on Autobahn',
    metadata: 'AutoTopNL · 37 lakh views · 1 year ago',
  },
  {
    id: '2',
    thumbnail: require('../assets/thumbnail-2.jpg'),
    profile: require('../assets/profile-2.png'),
    title: 'Oppenheimer | New Trailer',
    subtitle: 'A Film by Christopher Nolan',
    metadata: 'Universal Pictures · 7.2 crore views · 1 year ago',
  },
  {
    id: '3',
    thumbnail: require('../assets/thumbnail-3.jpg'),
    profile: require('../assets/profile-3.png'),
    title: 'Interstellar 4k HDR IMAX |',
    subtitle: 'Into the Black Hole - Gargantua 1/2',
    metadata: 'Apex Clips · 70 lakh views · 4 years ago',
  },
  {
    id: '4',
    thumbnail: require('../assets/thumbnail-4.jpg'),
    profile: require('../assets/profile-4.png'),
    title: 'Brian Cox explains quantum',
    subtitle: 'mechanics in 60 seconds - BBC News',
    metadata: 'BBC News · 84 lakh views · 10 years ago',
  },
  {
    id: '5',
    thumbnail: require('../assets/thumbnail-5.jpg'),
    profile: require('../assets/profile-5.png'),
    title: 'Batman Begins - The Will to Act ',
    subtitle: '(Training Scene HD)',
    metadata: 'S3r3nity Now · 94 lakh views · 11 years ago',
  },
  {
    id: '6',
    thumbnail: require('../assets/thumbnail-6.jpg'),
    profile: require('../assets/profile-6.png'),
    title: "You're on the Edge of Discovery, Can You",
    subtitle: 'Hear It? | Hypermind Music',
    metadata: 'Flow State Studio · 152k views · 2 months ago',
  },
  {
    id: '7',
    thumbnail: require('../assets/thumbnail-7.jpg'),
    profile: require('../assets/profile-7.png'),
    title: 'How This Telescope Searches For',
    subtitle: 'Aliens',
    metadata: 'Cleo Abram · 346k views · 2 years ago',
  },
];

